-- CreateTable
CREATE TABLE "AboutSettings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "heroEyebrow" TEXT NOT NULL DEFAULT 'About Our School',
    "heroTitle" TEXT NOT NULL DEFAULT 'St. Mary''s Secondary School-Manja',
    "heroDescription" TEXT NOT NULL DEFAULT 'Learn more about our school, our purpose, values and commitment to student development.',
    "welcomeEyebrow" TEXT NOT NULL DEFAULT 'Welcome',
    "mottoLabel" TEXT NOT NULL DEFAULT 'Our Motto',
    "missionLabel" TEXT NOT NULL DEFAULT 'Our Mission',
    "visionLabel" TEXT NOT NULL DEFAULT 'Our Vision',
    "valuesEyebrow" TEXT NOT NULL DEFAULT 'What Guides Us',
    "valuesTitle" TEXT NOT NULL DEFAULT 'Our Core Values',
    "valuesDescription" TEXT NOT NULL DEFAULT 'The principles that guide our school community and the development of our learners.',
    "governanceEyebrow" TEXT NOT NULL DEFAULT 'School Governance',
    "governanceTitle" TEXT NOT NULL DEFAULT 'Board of Governors',
    "governanceDescription" TEXT NOT NULL DEFAULT 'Our school is guided by committed leaders who support good governance, accountability and educational excellence.',
    "anthemEyebrow" TEXT NOT NULL DEFAULT 'Our Identity',
    "anthemTitle" TEXT NOT NULL DEFAULT 'School Anthem',
    "anthemText" TEXT NOT NULL DEFAULT 'Our school anthem reflects our identity, values, unity and commitment to excellence.',
    "ctaTitle" TEXT NOT NULL DEFAULT 'Join Our School Community',
    "ctaDescription" TEXT NOT NULL DEFAULT 'Begin your application or contact the school office for more information.',
    "ctaPrimaryText" TEXT NOT NULL DEFAULT 'Apply Now',
    "ctaPrimaryLink" TEXT NOT NULL DEFAULT '/admissions',
    "ctaSecondaryText" TEXT NOT NULL DEFAULT 'Contact Us',
    "ctaSecondaryLink" TEXT NOT NULL DEFAULT '/contact',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "GlobalLayoutSettings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "badgeUrl" TEXT NOT NULL DEFAULT '/branding/school-badge.png',
    "badgeAlt" TEXT NOT NULL DEFAULT 'St. Mary''s Secondary School Manja badge',
    "headerLocationLabel" TEXT NOT NULL DEFAULT 'Manja',
    "homeLabel" TEXT NOT NULL DEFAULT 'Home',
    "aboutLabel" TEXT NOT NULL DEFAULT 'About',
    "academicsLabel" TEXT NOT NULL DEFAULT 'Academics',
    "studentLifeLabel" TEXT NOT NULL DEFAULT 'Student Life',
    "mediaLabel" TEXT NOT NULL DEFAULT 'Media',
    "admissionsLabel" TEXT NOT NULL DEFAULT 'Admissions',
    "contactLabel" TEXT NOT NULL DEFAULT 'Contact',
    "topAdmissionsText" TEXT NOT NULL DEFAULT 'Online Admissions',
    "topAdmissionsLink" TEXT NOT NULL DEFAULT '/admissions',
    "aboutMenuTitle" TEXT NOT NULL DEFAULT 'Discover St. Mary''s',
    "aboutMenuSubtitle" TEXT NOT NULL DEFAULT 'Our identity, history, values and leadership.',
    "aboutLinks" TEXT NOT NULL DEFAULT '[{"label":"About Our School","href":"/about"},{"label":"Mission, Vision & Motto","href":"/about#mission"},{"label":"Leadership","href":"/#leadership"},{"label":"Board of Governors","href":"/about#governance"},{"label":"School Anthem","href":"/about#anthem"}]',
    "academicsMenuTitle" TEXT NOT NULL DEFAULT 'Academic Programmes',
    "academicsMenuSubtitle" TEXT NOT NULL DEFAULT 'Quality O-Level and A-Level education.',
    "academicsLinks" TEXT NOT NULL DEFAULT '[{"label":"Academics Overview","href":"/academics"},{"label":"O-Level Programme","href":"/academics#o-level"},{"label":"A-Level Programme","href":"/academics#a-level"},{"label":"Departments","href":"/academics#departments"},{"label":"Subjects Offered","href":"/academics#subjects"},{"label":"Academic Performance","href":"/academics#performance"}]',
    "studentLifeMenuTitle" TEXT NOT NULL DEFAULT 'Life Beyond the Classroom',
    "studentLifeMenuSubtitle" TEXT NOT NULL DEFAULT 'Talent, leadership and holistic development.',
    "studentLifeLinks" TEXT NOT NULL DEFAULT '[{"label":"Academic Life","href":"/academics#co-curricular"},{"label":"Clubs & Societies","href":"/academics#co-curricular"},{"label":"Sports","href":"/academics#co-curricular"},{"label":"Music, Dance & Drama","href":"/academics#co-curricular"},{"label":"Agriculture","href":"/academics#co-curricular"},{"label":"School Calendar","href":"/academics#calendar"}]',
    "mediaLinks" TEXT NOT NULL DEFAULT '[{"label":"Latest News","href":"/news"},{"label":"Photo Gallery","href":"/gallery"},{"label":"School Calendar","href":"/academics#calendar"}]',
    "footerDescription" TEXT NOT NULL DEFAULT 'Nurturing disciplined, responsible and academically excellent learners.',
    "footerQuickTitle" TEXT NOT NULL DEFAULT 'Quick Links',
    "footerQuickLinks" TEXT NOT NULL DEFAULT '[{"label":"About Us","href":"/about"},{"label":"Academics","href":"/academics"},{"label":"Admissions","href":"/admissions"},{"label":"Contact","href":"/contact"}]',
    "footerMediaTitle" TEXT NOT NULL DEFAULT 'Media',
    "footerMediaLinks" TEXT NOT NULL DEFAULT '[{"label":"Latest News","href":"/news"},{"label":"Gallery","href":"/gallery"},{"label":"Academic Life","href":"/academics#co-curricular"},{"label":"School Calendar","href":"/academics#calendar"}]',
    "footerContactTitle" TEXT NOT NULL DEFAULT 'Contact',
    "footerCopyrightText" TEXT NOT NULL DEFAULT 'All rights reserved.',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
